[satusehat]

url=https://api-satusehat.kemkes.go.id
dicom_pathsuffix=/dicom/v1/dicomWeb/studies
fhir_pathsuffix=/fhir-r4/v1
tz_name=Asia/Jakarta
ae_title=DCMROUTER
dicom_port=11112
dcm_dir=/in/
http_port=8080
mroc_client_url=http://localhost:8000
auto_delete_incoming=true
webhook_url=
webhook_user=
webhook_password=
organization_id=
client_key=
secret_key=
calling_ae_title=DCMROUTER
